version: 2
updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
  # Backend
  - package-ecosystem: "composer"
    directory: "backend"
    schedule:
      interval: "daily"