module.exports = {
	plugins: [
		// "sonarjs"
	],
	// extends: ["plugin:sonarjs/recommended"],
	/* rules: {
        "sonarjs/cognitive-complexity": "warn",
        "sonarjs/elseif-without-else": "warn",
        "sonarjs/max-switch-cases": "warn",
        "sonarjs/no-all-duplicated-branches": "warn",
        "sonarjs/no-collapsible-if": "warn",
        "sonarjs/no-collection-size-mischeck": "warn",
        "sonarjs/no-duplicate-string": "warn",
        "sonarjs/no-duplicated-branches": "warn",
        "sonarjs/no-element-overwrite": "warn",
        "sonarjs/no-empty-collection": "warn",
        "sonarjs/no-extra-arguments": "warn",
        "sonarjs/no-gratuitous-expressions": "warn",
        "sonarjs/no-identical-conditions": "warn",
        "sonarjs/no-identical-expressions": "warn",
        "sonarjs/no-identical-functions": "warn",
        "sonarjs/no-ignored-return": "warn",
        "sonarjs/no-inverted-boolean-check": "warn",
        "sonarjs/no-nested-switch": "warn",
        "sonarjs/no-nested-template-literals": "warn",
        "sonarjs/no-one-iteration-loop": "warn",
        "sonarjs/no-redundant-boolean": "warn",
        "sonarjs/no-redundant-jump": "warn",
        "sonarjs/no-same-line-conditional": "warn",
        "sonarjs/no-small-switch": "warn",
        "sonarjs/no-unused-collection": "warn",
        "sonarjs/no-use-of-empty-return-value": "warn",
        "sonarjs/no-useless-catch": "warn",
        "sonarjs/non-existent-operator": "warn",
        "sonarjs/prefer-immediate-return": "warn",
        "sonarjs/prefer-object-literal": "warn",
        "sonarjs/prefer-single-boolean-return": "warn",
        "sonarjs/prefer-while": "warn"
    } */
};
