name: Frontend Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
    paths:
      - 'frontend/**'
      
jobs:
  deploy:
    name: 'Frontend Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setup Node version
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      
      # Install dependencies
      - name: 'Install NPM dependencies'
        run: npm ci --force
        working-directory: frontend

      # Lint application
      - name: 'Lint application'
        run: 'npm run lint'
        working-directory: frontend

      # Build application
      - name: 'Build application'
        if: success()
        run: |
            npm run build
            echo "🎁 Application compiled!"
            ls -la dist
        working-directory: frontend

      # Connect to SSH and delete previous compilation
      - name: Delete previous compilation in server
        if: success()
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf contapp.mcfdez87.com/*

      # Copy compiled application with SCP
      - name: Upload compiled application
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "frontend/dist/*"
          target: "contapp.mcfdez87.com"
          strip_components: 2

      # Copy .htaccess file again
      - name: Copy .htaccess file again
        if: success()
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cp htaccess_contapp_front contapp.mcfdez87.com/.htaccess
